-- 이 시점(2026-09-03)까지 Hibernate ddl-auto=update가 실제로 만들어온 스키마를
-- pg_dump로 그대로 떠서 만든 베이스라인. 이미 데이터가 있는 기존 DB(로컬/Railway)에서는
-- Flyway가 이 버전을 "이미 적용됨"으로 표시만 하고 실행하지 않음(baseline-on-migrate).
-- 완전히 새로 시작하는 DB에서만 이 스크립트가 실제로 실행되어 처음부터 스키마를 만듦.

CREATE TABLE public.body_weight_logs (
    id bigint NOT NULL,
    recorded_date date NOT NULL,
    weight_kg double precision NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.body_weight_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.body_weight_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.exercises (
    id bigint NOT NULL,
    body_part character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    name_ja character varying(255),
    image_url character varying(500)
);

ALTER TABLE public.exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.routine_template_skips (
    id bigint NOT NULL,
    skipped_date date NOT NULL,
    template_id bigint NOT NULL
);

ALTER TABLE public.routine_template_skips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.routine_template_skips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.routine_templates (
    id bigint NOT NULL,
    body_part character varying(255) NOT NULL,
    day_of_week character varying(255) NOT NULL,
    exercise_name character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT routine_templates_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);

ALTER TABLE public.routine_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.routine_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255),
    provider character varying(255) NOT NULL,
    timezone character varying(255),
    birth_date date NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    nationality character varying(255) NOT NULL
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.workout_routines (
    id bigint NOT NULL,
    body_part character varying(255) NOT NULL,
    done boolean NOT NULL,
    exercise_name character varying(255) NOT NULL,
    scheduled_date date NOT NULL,
    user_id bigint NOT NULL,
    template_id bigint
);

ALTER TABLE public.workout_routines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workout_routines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.workout_sets (
    id bigint NOT NULL,
    reps integer NOT NULL,
    routine_id bigint NOT NULL,
    set_number integer NOT NULL,
    weight_kg double precision NOT NULL
);

ALTER TABLE public.workout_sets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workout_sets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.body_weight_logs
    ADD CONSTRAINT body_weight_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.routine_template_skips
    ADD CONSTRAINT routine_template_skips_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.routine_templates
    ADD CONSTRAINT routine_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workout_routines
    ADD CONSTRAINT workout_routines_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.workout_sets
    ADD CONSTRAINT workout_sets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.body_weight_logs
    ADD CONSTRAINT fk2rg2jg1uptgpxt0pdkn2jf7j5 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.routine_templates
    ADD CONSTRAINT fk5wpqv8ahl9dclyyn33ix3hb74 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.workout_routines
    ADD CONSTRAINT fkgx2uk2plua5r5yfpv8f5wq8a2 FOREIGN KEY (user_id) REFERENCES public.users(id);
